"""papersにdrive_file_id列を追加

Revision ID: 2bfe5dc2e804
Revises: b2ce69b60501
Create Date: 2026-09-11 15:47:53.829344
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bfe5dc2e804"
down_revision: str | None = "b2ce69b60501"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("drive_file_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "drive_file_id")
    # ### end Alembic commands ###
