"""reader_annotations, reader_positionsテーブルを追加

Revision ID: 74fd3b502ae2
Revises: 2bfe5dc2e804
Create Date: 2026-09-11 16:32:52.802951
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74fd3b502ae2"
down_revision: str | None = "2bfe5dc2e804"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reader_annotations",
        sa.Column(
            "annotation_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("view_mode", sa.Text(), nullable=False),
        sa.Column("sentence_id", sa.Text(), nullable=True),
        sa.Column("pdf_page", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("selected_text", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(view_mode <> 'reading' OR pdf_page IS NULL) AND (view_mode <> 'pdf' OR sentence_id IS NULL)",
            name="ck_reader_annotations_view_mode_fields",
        ),
        sa.CheckConstraint(
            "color IS NULL OR color IN ('yellow', 'red', 'blue')",
            name="ck_reader_annotations_color",
        ),
        sa.CheckConstraint(
            "kind IN ('note', 'highlight', 'bookmark')", name="ck_reader_annotations_kind"
        ),
        sa.CheckConstraint(
            "view_mode IN ('reading', 'pdf')", name="ck_reader_annotations_view_mode"
        ),
        sa.CheckConstraint(
            "pdf_page IS NULL OR pdf_page >= 1", name="ck_reader_annotations_pdf_page"
        ),
        sa.CheckConstraint("version >= 1", name="ck_reader_annotations_version"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.paper_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sentence_id"], ["sentences.sentence_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("annotation_id"),
    )
    op.create_index(
        "ix_reader_annotations_paper_kind", "reader_annotations", ["paper_id", "kind"], unique=False
    )
    op.create_index(
        "ix_reader_annotations_sentence_id", "reader_annotations", ["sentence_id"], unique=False
    )
    op.create_table(
        "reader_positions",
        sa.Column("paper_id", sa.Text(), nullable=False),
        sa.Column("view_mode", sa.Text(), nullable=False),
        sa.Column("sentence_id", sa.Text(), nullable=True),
        sa.Column("sentence_offset", sa.Double(), nullable=True),
        sa.Column("pdf_page", sa.Integer(), nullable=True),
        sa.Column("pdf_offset", sa.Double(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(view_mode <> 'reading' OR (pdf_page IS NULL AND pdf_offset IS NULL)) AND (view_mode <> 'pdf' OR (sentence_id IS NULL AND sentence_offset IS NULL))",
            name="ck_reader_positions_view_mode_fields",
        ),
        sa.CheckConstraint("view_mode IN ('reading', 'pdf')", name="ck_reader_positions_view_mode"),
        sa.CheckConstraint(
            "pdf_offset IS NULL OR (pdf_offset >= 0 AND pdf_offset <= 1)",
            name="ck_reader_positions_pdf_offset",
        ),
        sa.CheckConstraint(
            "pdf_page IS NULL OR pdf_page >= 1", name="ck_reader_positions_pdf_page"
        ),
        sa.CheckConstraint(
            "sentence_offset IS NULL OR (sentence_offset >= 0 AND sentence_offset <= 1)",
            name="ck_reader_positions_sentence_offset",
        ),
        sa.CheckConstraint("version >= 1", name="ck_reader_positions_version"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.paper_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sentence_id"], ["sentences.sentence_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("paper_id", "view_mode"),
    )
    op.create_index(
        "ix_reader_positions_sentence_id", "reader_positions", ["sentence_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reader_positions_sentence_id", table_name="reader_positions")
    op.drop_table("reader_positions")
    op.drop_index("ix_reader_annotations_sentence_id", table_name="reader_annotations")
    op.drop_index("ix_reader_annotations_paper_kind", table_name="reader_annotations")
    op.drop_table("reader_annotations")
    # ### end Alembic commands ###
